name: CI
on: [push]

jobs:
        deploy:
                if: github.ref == 'refs/heads/master'
                runs-on: [ubuntu-latest]
                steps:
                        - uses: actions/checkout@v2
                        - name: Setup mdbook
                        - uses: peaceiris/actions-mdbook@v1
                          with:
                                  mdbook-version: 'latest'
                        - run: mdbook build
                        - name: Deploy
                          uses: easingthemes/ssh-deploy@v2
                          env:
                                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                                  ARGS: "-rvzt --delete"
                                  SOURCE: "book/"
                                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                                  TARGET: ${{ secrets.REMOTE_TARGET }}
